_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.7.0
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 8
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.7.0
            "5": 0.18.3
            "8":
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 32
beta1:
    value: 0
beta2:
    value: 0.999
epochs:
    value: 10
label_smoothing:
    value: 1
learning_rate:
    value:
        discriminator: 0.0001
        generator: 0.0001
